schema_version = "1.0.0"
id = "mio3_mesh_tools"
name = "Mio3 Mesh Tools"
version = "0.10.0"
tagline = "Curve Edges, and Mesh Tools"
maintainer = "Mio"
type = "add-on"
tags = ["Mesh"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
website = "https://github.com/mio3io/mio3_mesh_tools"
copyright = ["2025 Mio"]

